jonatasbaldin/python-community-map

- communities.yaml
Added Python Users Group from Ceará, Brazil (PUG-CE)
> Added Python Users Group from Ceará, Brazil

- communities.yaml
Adds DerbyPy from Louisville, KY, USA
> Adds DerbyPy from Louisville, KY, USA

- communities.yaml
Adorei a ideia, Adicionada comunidade de Salvador
> Adicionada comunidade de Salvador

- communities.yaml
Also, fixed a few entries that were not in the same format as others.
> Added PyTche (Porto Alegre)

- communities.yaml
adding boston python user group.
> Add boston python

- communities.yaml
Adding Python Nigeria community to the list.
> Added entry for Python Nigeria

- communities.yaml
Added an entry for the PyAtl community.
> Added Atlanta python group

- style.css
> mobile footer

- communities.yaml
Adicionada a comunidade de Python em Manaus - AM.
> Add PyNorte - Manaus AM

- communities.yaml
Adding Python Argentina community to the list.
> Add Python Argentina

- communities.yaml
Agregar Comunidad Python Norte que agrupa los miembros del  norte de Argentina
> added python norte PyAr subcomunity

- communities.yaml
We want to share our work with other python developer around the world.
> Add Cameroon Python Academy Community

- .github/pull_request_template.md
- README.md
> Add information about tests, scrapping and a Pull Request Template file

- communities.yaml
> Adds Pydata BH.

- communities.yaml
> Adds Pydata Brasília.

- communities.yaml
- index.html
- style.css
Agregado soporte para Imagen Avatar y una pequeña descripción de la comunidad, reemplazado algunos usos de var por let. 
[preview](https://prnt.sc/lbaixa)
> added suport to avatar and short description

- communities.yaml
> Add GruPy-DF Logo

- communities.yaml
> Fix logo of Python Canarias

- communities.yaml
-  ✅ The community is a local community, and not a conference. This is not a map for events in a certain point in time!
-  ✅ The community added has a `name`, `lat`, `lng` and `url`
-  ✅ The URL is working. No 404 pleeeeeeeeeease!
-  ✅ The tests are passing
-  ✅ The tests are passing 🤷‍♀️
❤️
> Added San Diego to communities.yaml

- communities.yaml
```
$ npm test
> python-community-map@1.0.0 test /home/shako/REPOS/python-community-map
> npx mocha
communities
✓ test community schema
✓ all communities should have an unique pair of lat and lng (61ms)
2 passing (95ms)
```
> Added Azerbaijan PUG to the list

- communities.yaml
> add chennaipy community from india

- communities.yaml
- [x ] The community is a local community, and not a conference. This is not a map for events in a certain point in time!
- [x ] The community added has a `name`, `lat`, `lng` and `url`
- [ x] The URL is working. No 404 pleeeeeeeeeease!
❤️
> Add Python Mauritius User Group (PYMUG)

- communities.yaml
> added lexpy to list

- communities.yaml
Add comunity GruPy Blumenau SC in python community map.
❤️
> Add community GruPy Blumenau

- communities.yaml
> Add Python Venezuela

- communities.yaml
> updated pymug (mauritius)

- communities.yaml
> Add PyDelhi

- communities.yaml
- [✓] The community is a local community, and not a conference. This is not a map for events in a certain point in time!
- [✓] The community added has a `name`, `lat`, `lng` and `url`
- [✓] The URL is working. No 404 pleeeeeeeeeease!
- [✓] The tests are passing
❤️
> Adds Orlando Python

- communities.yaml
> Adding PyLadiesBH 

- communities.yaml
> Added Curitiba/Brazil community

- communities.yaml
> adiciona comunidade pyladies salvador

- communities.yaml
> Add Minsk Python Community and Belarus country
